# Generated by Django 4.2.18 on 2025-02-19 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StudentDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("dob", models.DateField()),
                ("address", models.TextField()),
                ("contact_number", models.CharField(max_length=15, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("physics_marks", models.FloatField()),
                ("english_marks", models.FloatField()),
                ("chemistry_marks", models.FloatField()),
            ],
        ),
    ]
